### ISSUE TITLE
Can tpu-mlir run in a windows docker container?

### ISSUE THREAD

**Issue by trainertry** [sophgo/tpu-mlir#129]

**Comment by trainertry** [comment]
root@e808b59acbd8:/workspace/tpu-mlir/python# /workspace/tpu-mlir/python/model_transform.py     --model_name yolov5s     --model_def /workspace\model_yolov5s/yolov5s.onnx     --input_shapes [[1,3,640,640]]     --mean 0.0,0.0,0.0     --scale 0.0039216,0.0039216,0.0039216     --keep_aspect_ratio     --pixel_format rgb     --output_names 350,498,646     --test_input /workspace\model_yolov5s/image/dog.jpg     --test_result yolov5s_top_outputs.npz     --mlir yolov5s.mlir
Traceback (most recent call last):
  File "/workspace/tpu-mlir/python/model_transform.py", line 17, in <module>
    from utils.mlir_parser import *
  File "/workspace/tpu-mlir/python/utils/mlir_parser.py", line 12, in <module>
    import mlir
ModuleNotFoundError: No module named 'mlir'

**Comment by raisinglc03** [comment]
run build.sh to compile this project
