### ISSUE TITLE
model_deploy.py ppocr_v3 --chip cv180x failed with `cvkcv180x tiu xor: wrong parameter`

### ISSUE THREAD

**Issue by Kahsolt** [sophgo/tpu-mlir#193]
using tpu-mlir commit hash: 7fe05c0b5e0801515101d97b97d6d08f4331a386

I'm trying to deploy [ppocr_v3](https://github.com/PaddlePaddle/PaddleCloud/blob/main/samples/PaddleOCR/PP-OCRv3.md) model on [MilkV-Duo](https://milkv.io/zh/duo) chip (CV1800B), so I converted model ckpt paddle -> onnx -> mlir, then generated calibration table, so far is ok... :)

But when I run the deploy command:

```
model_deploy.py \
  --chip cv180x \
  --mlir ppocrv3_rec.mlir \
  --quantize INT8 \
  --quant_input \
  --calibration_table ppocrv3_rec_cali_table \
  --model ppocrv3_rec.cvimodel
```

This error hits:

```
root@487524220d1c:/workspace/tmp# model_deploy.py \
  --chip cv180x \
  --mlir ppocrv3_rec.mlir \
  --quantize INT8 \
  --quant_input \
  --calibration_table ppocrv3_rec_cali_table \
  --model ppocrv3_rec.cvimodel
SOPHGO Toolchain v1.3.228-g19ca95e9-20230921
2024/10/19 22:37:21 - INFO : 
  load_config Preprocess args : 
        resize_dims           : [48, 640]
        keep_aspect_ratio     : True
        keep_ratio_mode       : letterbox
        pad_value             : 0
        pad_type              : center
        input_dims            : [48, 640]
        --------------------------
        mean                  : [0.0, 0.0, 0.0]
        scale                 : [0.0039216, 0.0039216, 0.0039216]
        --------------------------
        pixel_format          : rgb
        channel_format        : nchw

[Running]: tpuc-opt ppocrv3_rec.mlir --chip-assign="chip=cv180x" --import-calibration-table="file=ppocrv3_rec_cali_table asymmetric=False" --chip-top-optimize --convert-top-to-tpu="mode=INT8  asymmetric=False linear_quant_mode=NORMAL doWinograd=False ignore_f16_overflow=False" --canonicalize -o ppocrv3_rec_cv180x_int8_sym_tpu.mlir 
[Success]: tpuc-opt ppocrv3_rec.mlir --chip-assign="chip=cv180x" --import-calibration-table="file=ppocrv3_rec_cali_table asymmetric=False" --chip-top-optimize --convert-top-to-tpu="mode=INT8  asymmetric=False linear_quant_mode=NORMAL doWinograd=False ignore_f16_overflow=False" --canonicalize -o ppocrv3_rec_cv180x_int8_sym_tpu.mlir 
[Running]: tpuc-opt ppocrv3_rec_cv180x_int8_sym_tpu.mlir --mlir-disable-threading --strip-io-quant="quant_input=True quant_output=False" --chip-tpu-optimize --distribute='num_device=1' --weight-reorder  --subnet-divide="dynamic=False" --op-reorder --layer-group="opt=2" --parallel='num_core=1' --address-assign -o ppocrv3_rec_cv180x_int8_sym_final.mlir 

...

GmemAllocator use FitFirstAssign
[Success]: tpuc-opt ppocrv3_rec_cv180x_int8_sym_tpu.mlir --mlir-disable-threading --strip-io-quant="quant_input=True quant_output=False" --chip-tpu-optimize --distribute='num_device=1' --weight-reorder  --subnet-divide="dynamic=False" --op-reorder --layer-group="opt=2" --parallel='num_core=1' --address-assign -o ppocrv3_rec_cv180x_int8_sym_final.mlir 
[Running]: tpuc-opt ppocrv3_rec_cv180x_int8_sym_final.mlir --codegen="model_file=ppocrv3_rec.cvimodel embed_debug_info=false model_version=latest" -o /dev/null 
  [oc_pos=0] cur_oc 2, stepSize 128, compressedSize 144, SKIP
  [oc_pos=0] cur_oc 2, stepSize 128, compressedSize 144, SKIP
  [oc_pos=112] cur_oc 4, stepSize 512, compressedSize 528, SKIP
  [oc_pos=16] cur_oc 4, stepSize 512, compressedSize 528, SKIP
  [oc_pos=208] cur_oc 4, stepSize 1024, compressedSize 1040, SKIP
  [oc_pos=48] cur_oc 4, stepSize 1024, compressedSize 1040, SKIP
  [oc_pos=72] cur_oc 4, stepSize 1024, compressedSize 1040, SKIP
  [oc_pos=4] cur_oc 4, stepSize 1024, compressedSize 1040, SKIP
  [oc_pos=40] cur_oc 4, stepSize 1024, compressedSize 1040, SKIP
  [oc_pos=4] cur_oc 4, stepSize 480, compressedSize 512, SKIP
cvkcv180x tiu xor: wrong parameter
tpuc-opt: /home/jenkins/workspace/tpu-mlir/lib/Backend/CV18xx/Kernel/TgBf16SoftmaxKernel.cpp:256: void tpu_mlir::backend::TgSoftmaxKernel::softmaxLargeSizeHandler(): Assertion `tl_lut_reciprocal_result' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: tpuc-opt ppocrv3_rec_cv180x_int8_sym_final.mlir --init "--codegen=model_file=ppocrv3_rec.cvimodel embed_debug_info=false model_version=latest" --deinit --mlir-print-debuginfo -o /dev/null
 #0 0x000055bdfa50ac37 (/workspace/tpu-mlir/bin/tpuc-opt+0x5e5c37)
 #1 0x000055bdfa50895e (/workspace/tpu-mlir/bin/tpuc-opt+0x5e395e)
 #2 0x000055bdfa50b5ba (/workspace/tpu-mlir/bin/tpuc-opt+0x5e65ba)
 #3 0x00007f7fa9061520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f7fa90b59fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f7fa9061476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f7fa90477f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f7fa904771b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f7fa9058e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000055bdfaca69bf (/workspace/tpu-mlir/bin/tpuc-opt+0xd819bf)
#10 0x000055bdfacaa452 (/workspace/tpu-mlir/bin/tpuc-opt+0xd85452)
#11 0x000055bdfacaa969 (/workspace/tpu-mlir/bin/tpuc-opt+0xd85969)
#12 0x000055bdfab1377f (/workspace/tpu-mlir/bin/tpuc-opt+0xbee77f)
#13 0x000055bdfaa8e315 (/workspace/tpu-mlir/bin/tpuc-opt+0xb69315)
#14 0x000055bdfabbbf95 (/workspace/tpu-mlir/bin/tpuc-opt+0xc96f95)
#15 0x000055bdfabbbe74 (/workspace/tpu-mlir/bin/tpuc-opt+0xc96e74)
#16 0x000055bdfabbe1bd (/workspace/tpu-mlir/bin/tpuc-opt+0xc991bd)
#17 0x000055bdfabbdf42 (/workspace/tpu-mlir/bin/tpuc-opt+0xc98f42)
#18 0x000055bdfab9fc44 (/workspace/tpu-mlir/bin/tpuc-opt+0xc7ac44)
#19 0x000055bdfb2271b4 (/workspace/tpu-mlir/bin/tpuc-opt+0x13021b4)
#20 0x000055bdfb2277e1 (/workspace/tpu-mlir/bin/tpuc-opt+0x13027e1)
#21 0x000055bdfb229c88 (/workspace/tpu-mlir/bin/tpuc-opt+0x1304c88)
#22 0x000055bdfa4fc47b (/workspace/tpu-mlir/bin/tpuc-opt+0x5d747b)
#23 0x000055bdfa4fb844 (/workspace/tpu-mlir/bin/tpuc-opt+0x5d6844)
#24 0x000055bdfb42da08 (/workspace/tpu-mlir/bin/tpuc-opt+0x1508a08)
#25 0x000055bdfa4f5b4a (/workspace/tpu-mlir/bin/tpuc-opt+0x5d0b4a)
#26 0x000055bdfa4f6014 (/workspace/tpu-mlir/bin/tpuc-opt+0x5d1014)
#27 0x000055bdfa4f4d99 (/workspace/tpu-mlir/bin/tpuc-opt+0x5cfd99)
#28 0x00007f7fa9048d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#29 0x00007f7fa9048e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#30 0x000055bdfa4f49f5 (/workspace/tpu-mlir/bin/tpuc-opt+0x5cf9f5)
Aborted
Traceback (most recent call last):
  File "/workspace/tpu-mlir/python/tools/model_deploy.py", line 320, in <module>
    tool.build_model()
  File "/workspace/tpu-mlir/python/tools/model_deploy.py", line 219, in build_model
    mlir_to_model(self.tpu_mlir, self.model, self.final_mlir, self.dynamic,
  File "/workspace/tpu-mlir/python/utils/mlir_shell.py", line 165, in mlir_to_model
    _os_system(cmd)
  File "/workspace/tpu-mlir/python/utils/mlir_shell.py", line 50, in _os_system
    raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt ppocrv3_rec_cv180x_int8_sym_final.mlir --codegen="model_file=ppocrv3_rec.cvimodel embed_debug_info=false model_version=latest" -o /dev/null 
```

I found the core error message is:

```
cvkcv180x tiu xor: wrong parameter
tpuc-opt: /home/jenkins/workspace/tpu-mlir/lib/Backend/CV18xx/Kernel/TgBf16SoftmaxKernel.cpp:256: void tpu_mlir::backend::TgSoftmaxKernel::softmaxLargeSizeHandler(): Assertion `tl_lut_reciprocal_result' failed.
```

then I dig into tpu-mlir's code:

```
// https://github.com/sophgo/tpu-mlir/blob/master/lib/Backend/CV18xx/Kernel/TgBf16SoftmaxKernel.cpp
cvk_tl_t *tl_lut_reciprocal_result =
   CV18xx::lmem_alloc_tensor(lut_result_shape, fmt, eu_align);
ASSERT(tl_lut_reciprocal_result);
```

I don't know what here memory is allocated for, but this model ppocr_v3 does use many Softmax layers.
**Does this mean the memory on chip is not enough for running this model?**

Another hint, when replacing `--chip cv180x` with `--chip cv181x`, no error occur.

**Comment by Megadeth9919** [comment]
Could you provide the ONNX model?

**Comment by zjj421** [comment]
@Kahsolt Hello, I meet this error too, did you solved this problem?

**Comment by Kahsolt** [comment]
> Could you provide the ONNX model?

Yes, here please :)

[ch_PP-OCRv3_rec_infer.zip](https://github.com/user-attachments/files/17694600/ch_PP-OCRv3_rec_infer.zip)

**Comment by Megadeth9919** [comment]
> > Could you provide the ONNX model?
> 
> Yes, here please :)
> 
> [ch_PP-OCRv3_rec_infer.zip](https://github.com/user-attachments/files/17694600/ch_PP-OCRv3_rec_infer.zip)

The model looks like there's no problem, I need “ppocrv3_rec.mlir” and “ppocrv3_rec_cali_table” to reproduce it

**Comment by Megadeth9919** [comment]
> > > > Could you provide the ONNX model?
> > > 
> > > 
> > > Yes, here please :)
> > > [ch_PP-OCRv3_rec_infer.zip](https://github.com/user-attachments/files/17694600/ch_PP-OCRv3_rec_infer.zip)
> > 
> > 
> > The model looks like there's no problem, I need “ppocrv3_rec.mlir” and “ppocrv3_rec_cali_table” to reproduce it
> 
> Thanks for tracking the problem! :) Here it is:
> 
> [ppocrv3_rec_mlir_and_cali_table.zip](https://github.com/user-attachments/files/17776078/ppocrv3_rec_mlir_and_cali_table.zip)
> 
> And this is how I convert this onnx -> mlir:
> 
> ```shell
> model_transform.py \
>   --model_name ppocrv3_rec \
>   --model_def ch_PP-OCRv3_rec_infer.onnx \
>   --input_shapes '[[1,3,32,320]]' \
>   --mean 127.5,127.5,127.5 \
>   --scale 0.0078125,0.0078125,0.0078125 \
>   --keep_aspect_ratio \
>   --test_input crop_9.jpg \
>   --test_result ppocrv3_rec_outputs.npz \
>   --debug \
>   --mlir ppocrv3_rec.mlir
> ```
> 
> where `crop_9.jpg` is this image file:
> 
> ![crop_9](https://private-user-images.githubusercontent.com/22111194/386621462-ee34fc0c-ead5-4dac-b17e-84ba9681d4cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzgwMjksIm5iZiI6MTczMTY3NzcyOSwicGF0aCI6Ii8yMjExMTE5NC8zODY2MjE0NjItZWUzNGZjMGMtZWFkNS00ZGFjLWIxN2UtODRiYTk2ODFkNGNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEzMzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNWFiN2M1MmUyNjE0ZjZlYjNkNjlkZGRiZjNkZTFmYTM2MmIxNDkyYmQxYWYwZDAyYjg5ZTU0ODQ3ZjNiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cE1CUvYaaY4Vj9kq_b8M6T_-zjRBiEQMiMAHDEuBxWc)

After removing the last layer (softmax) of the model, it works, so I guess the problem is due to insufficient local memory on the 
 TPU. A method is to calculate the last layer as post-processing using the CPU.
[ppocrv3_rec_withoutlast.zip](https://github.com/user-attachments/files/17784038/ppocrv3_rec_withoutlast.zip)

**Comment by Megadeth9919** [comment]
After removing the last layer (softmax) of the model, it works, so I guess the problem is due to insufficient local memory on the 
 TPU. A method is to calculate the last layer as post-processing using the CPU.
[ppocrv3_rec_withoutlast.zip](https://github.com/user-attachments/files/17784038/ppocrv3_rec_withoutlast.zip)

**Comment by Kahsolt** [comment]
Thanks for the fix, I'll try :)
